import time
import numpy as np
import SimpleITK as sitk
from skimage.filters import threshold_otsu
from utils_pre import numpy_to_sitk
import pandas as pd
import numpy as np
from sklearn.decomposition import FastICA

# Configs 
REGISTRATION_CANDIDATES = [0.01, 0.05, 0.10]
REGISTRATION_BASELINE = 0.50

def crop_3D(data, margin_xy=10, margin_z=3):
    """
    This funciton cropts the IRM volume to remove empty space around the tissue
    """
    # 4D to 3D 
    if data.ndim == 4:
        vol_3d = np.max(data, axis=3) 
    else:
        vol_3d = data

    # XY Projection 
    proj_xy = np.max(vol_3d, axis=2) 
    
    try:
        thresh_xy = threshold_otsu(proj_xy)
        mask_xy = proj_xy > thresh_xy
    except Exception as e:
        return data, None, {"Error": "Otsu Failed"}
    
    coords_xy = np.where(mask_xy)
    if len(coords_xy[0]) == 0: return data, None, {"Error": "Empty Mask XY"}
    
    x_min, x_max = np.min(coords_xy[0]), np.max(coords_xy[0])
    y_min, y_max = np.min(coords_xy[1]), np.max(coords_xy[1])

    # YZ Projection
    proj_yz = np.max(vol_3d, axis=0)
    
    try:
        thresh_yz = threshold_otsu(proj_yz)
        mask_yz = proj_yz > thresh_yz
    except:
        return data, None, {"Error": "Otsu YZ Failed"}

    coords_yz = np.where(mask_yz)
    if len(coords_yz[1]) == 0: return data, None, {"Error": "Empty Mask YZ"}
    
    z_min, z_max = np.min(coords_yz[1]), np.max(coords_yz[1])

    # Crapping + Margin 
    x_min = max(0, x_min - margin_xy)
    x_max = min(data.shape[0], x_max + margin_xy)

    y_min = max(0, y_min - margin_xy)
    y_max = min(data.shape[1], y_max + margin_xy)

    z_min = max(0, z_min - margin_z)
    z_max = min(data.shape[2], z_max + margin_z)

    if data.ndim == 4:
        cropped_data = data[x_min:x_max, y_min:y_max, z_min:z_max, :]
    else:
        cropped_data = data[x_min:x_max, y_min:y_max, z_min:z_max]

    stats = {"Crop_Vol": cropped_data.size,
        "Orig_Vol": data.size,
        "Coords": (x_min, x_max, y_min, y_max, z_min, z_max)}
    
    return cropped_data, (x_min, x_max, y_min, y_max, z_min, z_max), stats

def get_drift(tx, is_rigid):
    """
    Calculate the drift generated by the registration transformation
    """
    params = np.array(tx.GetParameters())
    if is_rigid: 
        return np.linalg.norm(params[3:])
    
    n = len(params)//3
    vectors_mag = np.sqrt(params[:n]**2 + params[n:2*n]**2 + params[2*n:]**2)
    return np.mean(vectors_mag)

def _execute_reg(fixed, moving, mask, rate, mode):
    """
    Fonction helper to run registration rigid or bspline 
    """
    R = sitk.ImageRegistrationMethod()
    R.SetMetricAsMattesMutualInformation(50)
    R.SetMetricFixedMask(mask)
    R.SetMetricSamplingStrategy(R.RANDOM)
    R.SetMetricSamplingPercentage(rate)
    
    if mode == "Rigid":
        R.SetOptimizerAsGradientDescent(learningRate=1.0, numberOfIterations=30)
        R.SetOptimizerScalesFromPhysicalShift()
        tx = sitk.CenteredTransformInitializer(fixed, moving, sitk.Euler3DTransform())
    else: 
        tx = sitk.BSplineTransformInitializer(fixed, [3,3,3]) 
        R.SetOptimizerAsGradientDescent(learningRate=5.0, numberOfIterations=20)
        
    R.SetInitialTransform(tx)
    
    st = time.time()
    out_tx = R.Execute(fixed, moving)
    return out_tx, time.time()-st

def run_registration_benchmark(data, spacing):
    """
    Benchmark function to evaluate registration stability
    """
    results = []
    
    if data.ndim < 4 or data.shape[3] < 2: 
        return []
    
    f_img = numpy_to_sitk(data[..., 0], spacing)
    
    otsu_filter = sitk.OtsuThresholdImageFilter()
    otsu_filter.SetInsideValue(1)
    otsu_filter.SetOutsideValue(0)
    m_img = sitk.Cast(otsu_filter.Execute(f_img), sitk.sitkUInt8)


    mov_img = numpy_to_sitk(data[..., 1], spacing)
    for mode in ["Rigid", "BSpline"]:
        is_rigid = (mode == "Rigid")
        
        try:
            base_tx, base_t = _execute_reg(f_img, mov_img, m_img, REGISTRATION_BASELINE, mode)
            base_drift = get_drift(base_tx, is_rigid)
            
            for rate in REGISTRATION_CANDIDATES:
                cand_tx, cand_t = _execute_reg(f_img, mov_img, m_img, rate, mode)
                cand_drift = get_drift(cand_tx, is_rigid)
                
                stability_error = abs(base_drift - cand_drift)

                results.append({
                    "Reg_Type": mode, 
                    "Sampling_Rate": rate,
                    "Time_sec": round(cand_t, 3),
                    "Speedup": round(base_t/cand_t, 1) if cand_t > 0 else 0,
                    "Ref_Drift_mm": round(base_drift, 2), 
                    "Stability_Err_mm": round(stability_error, 3)
                })
        except Exception as e:
            print(f"Test failed for {mode}: {e}")
            
    return results

def ICA_test(data, prefix, n_components):
    """
    Perform ICA decomposition on 4D MRI data and extract components
    """
    
    meta_records = [] 
    heavy_data = {}   

    if data.ndim != 4:
        return None, None 

    nx, ny, nz, nt = data.shape
    # Reshape for scikit learn
    X = data.reshape(-1, nt).T 
    
    ica = FastICA(n_components=n_components, random_state=42)
    
    try:
        S_ = ica.fit_transform(X)
        A_ = ica.mixing_        
    except Exception as e:
        print(f"Erreur ICA sur {prefix}: {e}")
        return pd.DataFrame(), {} 
    
    real_n_components = S_.shape[1]
    # Extract components and compute scores
    for comp_idx in range(real_n_components):
        
        uid = f"{prefix}_C{comp_idx}"
        

        temporal_curve = S_[:, comp_idx]
        spatial_vector = A_[:, comp_idx]
        spatial_vol_3d = spatial_vector.reshape(nx, ny, nz)
        
        score_smooth = np.corrcoef(temporal_curve[:-1], temporal_curve[1:])[0, 1]
        score_power = np.var(temporal_curve)

        meta_records.append({
            "Component": n_components,
            "UID": uid,
            "Patient_Source": prefix,
            "Comp_ID": comp_idx,
            "Score_Lissage": round(score_smooth, 4),
            "Score_Power": round(score_power, 4)})
        
        heavy_data[uid] = {"temporal": temporal_curve,
            "spatial": spatial_vol_3d }

    return pd.DataFrame(meta_records), heavy_data